# documentation: https://wordpress.org 
# slogan: Wordpress is open source software you can use to create a beautiful website, blog, or app.
# tags: cms, blog, content, management, mariadb
# logo: svgs/wordpress.svg

services:
  wordpress:
    image: wordpress:php8.2-fpm
    volumes:
      - ./wordpress-files:/var/www/html
      - ./php/wp-php.ini:/usr/local/etc/php/conf.d/wp-php.ini
    environment:
      - SERVICE_FQDN_WORDPRESS
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=$SERVICE_USER_WORDPRESS
      - WORDPRESS_DB_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress-files:/var/www/html
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - wordpress
      
  mariadb:
    image: mariadb:11
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=$SERVICE_USER_WORDPRESS
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_WORDPRESS
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 20s
      retries: 10
      
  redis:
    image: redis:latest
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis-data:/data
    command: ["redis-server", "--appendonly yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5      

  phpmyadmin:
    image: lscr.io/linuxserver/phpmyadmin:latest
    depends_on:
      - mariadb
    ports:
      - "8070:80"      
    environment:
      - PMA_HOST=mariadb
      - PMA_PASSWORD=$SERVICE_PASSWORD_ROOT
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - PMA_ARBITRARY=1
      - PMA_ABSOLUTE_URI=$SERVICE_FQDN_WORDPRESS
    volumes:
      - ./phpmyadmin-config:/config
      - ./pma-custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15      
